CREATE TABLESPACE Z88011U1
  IN Z88011
  USING STOGROUP ZXPUSER
  PRIQTY 20 SECQTY 20
  ERASE NO
  DEFINE YES
  LOCKSIZE PAGE LOCKMAX SYSTEM
  BUFFERPOOL BP0
  SEGSIZE 16
  MAXPARTITIONS 256
  DSSIZE 4G
  CCSID UNICODE
  CLOSE NO
  COMPRESS YES;

CREATE TABLE Z88011.PLAN_TABLE
(
    "QUERYNO"            INTEGER      NOT NULL,
    "QBLOCKNO"           SMALLINT     NOT NULL,
    "APPLNAME"           VARCHAR(24)  NOT NULL,
    "PROGNAME"           VARCHAR(128) NOT NULL,
    "PLANNO"             SMALLINT     NOT NULL,
    "METHOD"             SMALLINT     NOT NULL,
    "CREATOR"            VARCHAR(128) NOT NULL,
    "TNAME"              VARCHAR(128) NOT NULL,
    "TABNO"              SMALLINT     NOT NULL,
    "ACCESSTYPE"         CHAR(2)      NOT NULL,
    "MATCHCOLS"          SMALLINT     NOT NULL,
    "ACCESSCREATOR"      VARCHAR(128) NOT NULL,
    "ACCESSNAME"         VARCHAR(128) NOT NULL,
    "INDEXONLY"          CHAR(1)      NOT NULL,
    "SORTN_UNIQ"         CHAR(1)      NOT NULL,
    "SORTN_JOIN"         CHAR(1)      NOT NULL,
    "SORTN_ORDERBY"      CHAR(1)      NOT NULL,
    "SORTN_GROUPBY"      CHAR(1)      NOT NULL,
    "SORTC_UNIQ"         CHAR(1)      NOT NULL,
    "SORTC_JOIN"         CHAR(1)      NOT NULL,
    "SORTC_ORDERBY"      CHAR(1)      NOT NULL,
    "SORTC_GROUPBY"      CHAR(1)      NOT NULL,
    "TSLOCKMODE"         CHAR(3)      NOT NULL,
    "TIMESTAMP"          CHAR(16)     NOT NULL,
    "REMARKS"            VARCHAR(762) NOT NULL,

    "PREFETCH"           CHAR(1)      NOT NULL WITH DEFAULT,
    "COLUMN_FN_EVAL"     CHAR(1)      NOT NULL WITH DEFAULT,
    "MIXOPSEQ"           SMALLINT     NOT NULL WITH DEFAULT,
    "VERSION"            VARCHAR(122) NOT NULL WITH DEFAULT,
    "COLLID"             VARCHAR(128) NOT NULL WITH DEFAULT,

    "ACCESS_DEGREE"      SMALLINT,
    "ACCESS_PGROUP_ID"   SMALLINT,
    "JOIN_DEGREE"        SMALLINT,
    "JOIN_PGROUP_ID"     SMALLINT,
    "SORTC_PGROUP_ID"    SMALLINT,
    "SORTN_PGROUP_ID"    SMALLINT,
    "PARALLELISM_MODE"   CHAR(1),
    "MERGE_JOIN_COLS"    SMALLINT,
    "CORRELATION_NAME"   VARCHAR(128),

    "PAGE_RANGE"         CHAR(1)      NOT NULL WITH DEFAULT,
    "JOIN_TYPE"          CHAR(1)      NOT NULL WITH DEFAULT,
    "GROUP_MEMBER"       VARCHAR(24)  NOT NULL WITH DEFAULT,

    "IBM_SERVICE_DATA"   VARCHAR(254) FOR BIT DATA NOT NULL WITH DEFAULT,

    "WHEN_OPTIMIZE"      CHAR(1)      NOT NULL WITH DEFAULT,
    "QBLOCK_TYPE"        CHAR(6)      NOT NULL WITH DEFAULT,
    "BIND_TIME"          TIMESTAMP    NOT NULL WITH DEFAULT,
    "OPTHINT"            VARCHAR(128) NOT NULL WITH DEFAULT,
    "HINT_USED"          VARCHAR(128) NOT NULL WITH DEFAULT,
    "PRIMARY_ACCESSTYPE" CHAR(1)      NOT NULL WITH DEFAULT,

    "PARENT_QBLOCKNO"    SMALLINT     NOT NULL WITH DEFAULT,
    "TABLE_TYPE"         CHAR(1),
    "TABLE_ENCODE"       CHAR(1)      NOT NULL WITH DEFAULT,
    "TABLE_SCCSID"       SMALLINT     NOT NULL WITH DEFAULT,
    "TABLE_MCCSID"       SMALLINT     NOT NULL WITH DEFAULT,
    "TABLE_DCCSID"       SMALLINT     NOT NULL WITH DEFAULT,

    "ROUTINE_ID"         INTEGER      NOT NULL WITH DEFAULT,
    "CTEREF"             SMALLINT     NOT NULL WITH DEFAULT,
    "STMTTOKEN"          VARCHAR(240),

    "PARENT_PLANNO"      SMALLINT     NOT NULL WITH DEFAULT,
    "BIND_EXPLAIN_ONLY"  CHAR(1)      NOT NULL WITH DEFAULT,
    "SECTNOI"            INTEGER      NOT NULL WITH DEFAULT,
    "EXPLAIN_TIME"       TIMESTAMP    NOT NULL WITH DEFAULT,

    "MERGC"              CHAR(1)      NOT NULL WITH DEFAULT,
    "MERGN"              CHAR(1)      NOT NULL WITH DEFAULT,
    "SCAN_DIRECTION"     CHAR(1),

    "EXPANSION_REASON"   CHAR(2)      NOT NULL WITH DEFAULT,
    "PER_STMT_ID"        BIGINT       NOT NULL WITH DEFAULT,

    "AP_PLANID"          CHAR(16) FOR BIT DATA
)
    IN Z88011.Z88011U1
CCSID UNICODE
;

CREATE INDEX Z88011.PLAN_TABLE_HINT_IX
    ON Z88011.PLAN_TABLE
        ( "QUERYNO", "APPLNAME", "PROGNAME", "VERSION", "COLLID", "OPTHINT" );

CREATE INDEX Z88011.PLAN_TABLE_APID_IX
    ON Z88011.PLAN_TABLE
        ( "AP_PLANID" );
