-- DB2 schema for LIBRARY demo
CREATE SCHEMA LIBRARY;

CREATE TABLE LIBRARY.USER (
    USER_ID_NUM   BIGINT       GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    USER_ID       CHAR(10)     NOT NULL,
    NAME          VARCHAR(100) NOT NULL,
    REGISTERED_AT TIMESTAMP    NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    CONSTRAINT PK_USER PRIMARY KEY (USER_ID_NUM),
    CONSTRAINT UQ_USER_ID UNIQUE (USER_ID)
);

CREATE TABLE LIBRARY.BOOK (
    BOOK_ID_NUM   BIGINT        GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    BOOK_ID       CHAR(10)      NOT NULL,
    TITLE         VARCHAR(200)  NOT NULL,
    AUTHOR        VARCHAR(200),
    STATUS        CHAR(1)       NOT NULL DEFAULT 'A',
    CONSTRAINT PK_BOOK PRIMARY KEY (BOOK_ID_NUM),
    CONSTRAINT UQ_BOOK_ID UNIQUE (BOOK_ID)
);

CREATE TABLE LIBRARY.LOAN (
    LOAN_ID_NUM   BIGINT       GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    USER_ID       CHAR(10)     NOT NULL,
    BOOK_ID       CHAR(10)     NOT NULL,
    LOAN_DATE     DATE         NOT NULL,
    DUE_DATE      DATE         NOT NULL,
    RETURN_DATE   DATE,
    CONSTRAINT PK_LOAN PRIMARY KEY (LOAN_ID_NUM),
    CONSTRAINT FK_LOAN_USER FOREIGN KEY (USER_ID)
        REFERENCES LIBRARY.USER (USER_ID),
    CONSTRAINT FK_LOAN_BOOK FOREIGN KEY (BOOK_ID)
        REFERENCES LIBRARY.BOOK (BOOK_ID)
);

-- Optional view to expose computed business LOAN_ID for debugging/querying
CREATE OR REPLACE VIEW LIBRARY.V_LOAN AS
SELECT
  LOAN_ID_NUM,
  'L' || SUBSTR('000000000' || CHAR(LOAN_ID_NUM), LENGTH('000000000' || CHAR(LOAN_ID_NUM)) - 8, 9) AS LOAN_ID,
  USER_ID,
  BOOK_ID,
  LOAN_DATE,
  DUE_DATE,
  RETURN_DATE
FROM LIBRARY.LOAN;
