server:
  port: 8080

mq:
  library:
    request-queue: Z88011.MQZ3.QLOCAL
    reply-queue: Z88011.MQZ3.REPLYTO.QLOCAL
    timeout: 60s
  connection:
    host: 204.90.115.200
    port: 1414
    channel: WAS.JMS.SVRCONN
    queue-manager: CSQ9
    user: Z88011
    password: TAX98TUX

logging:
  level:
    com.company.library: DEBUG
    org.springframework.jms: DEBUG
    org.springframework.jms.connection: DEBUG
    org.springframework.jms.core: DEBUG
    com.ibm.msg.client: DEBUG
    com.ibm.mq: DEBUG