---
- name: Run host job (batch program)
  hosts: zos_xplore
  gather_facts: false

  vars:
    jcl_pds: "{{ hlq }}.JCL"
    run_member: "LIBMQTST"
    max_rc_run: 0

  environment: "{{ environment_vars }}"

  collections:
    - ibm.ibm_zos_core

  tasks:
    - name: Submit run job {{ run_member }}
      zos_job_submit:
        src: "{{ jcl_pds }}({{ run_member }})"
        location: data_set
        wait_time_s: 300
        return_output: true
        max_rc: "{{ max_rc_run }}"
      register: run_job

    - name: Show run RC
      debug:
        msg: "Run RC={{ run_job.jobs[0].ret_code.msg }}"
