all:
  hosts:
    zos_xplore:
      ansible_host: 204.90.115.200   # IBM Z XPlore host (example)
      ansible_user: Z86422           # replace with your user
      ansible_ssh_port: 22
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
